#!/bin/bash

echo "Running ktlintCheck pre-commit hook"

./gradlew KtlintCheck

STATUS=$?

# return exit code 1 if running check fails
[ $STATUS -ne 0 ] && exit 1
exit 0

echo "Completed ktlintCheck pre-commit hook."
